import psycopg2
from psycopg2.extras import execute_values
import random
from datetime import datetime, timedelta

def connect_db():
    return psycopg2.connect(
        dbname="stayspot_db", 
        user="postgres", 
        host="localhost", 
        port="5432"
    )


def fetch_existing_ids(cursor, table_name):
    """Fetches all primary keys from a table so we can use them as valid Foreign Keys."""
    cursor.execute(f"SELECT id FROM {table_name};")
    # cursor.fetchall() returns a list of tuples: [(1,), (2,), (3,)]
    # We use a list comprehension to flatten it into: [1, 2, 3]
    return [row[0] for row in cursor.fetchall()]

def generate_and_insert_bookings(cursor, guest_ids, property_ids, num_bookings):
    print(f"Generating {num_bookings} bookings...")
    booking_data = []
    
    # We use a set (like std::unordered_set) to track who is currently checked in
    # This ensures we don't violate your Day 3 partial index!
    active_checkins = set()
    
    statuses = ['COMPLETED', 'CONFIRMED', 'CHECKED_IN']
    
    for _ in range(num_bookings):
        guest_id = random.choice(guest_ids)
        property_id = random.choice(property_ids)
        total_cost = round(random.uniform(100.0, 2000.0), 2)
        
        # Determine status, respecting the partial index rule
        status = random.choice(statuses)
        if status == 'CHECKED_IN':
            if guest_id in active_checkins:
                status = 'CONFIRMED' # Fallback to avoid duplicate active stay
            else:
                active_checkins.add(guest_id)
                
        # Generate a random timestamp within the last year
        random_days_ago = random.randint(0, 365)
        created_at = datetime.now() - timedelta(days=random_days_ago)
        
        booking_data.append((guest_id, property_id, total_cost, status, created_at))

    insert_query = """
        INSERT INTO bookings (guest_id, property_id, total_cost, status, created_at) 
        VALUES %s
    """
    execute_values(cursor, insert_query, booking_data)
    print("Bookings inserted successfully!")

def generate_and_insert_audit_logs(cursor, guest_ids, num_logs):
    print(f"Generating {num_logs} historical wallet audit logs...")
    log_data = []
    
    for _ in range(num_logs):
        guest_id = random.choice(guest_ids)
        amount_changed = round(random.uniform(10.0, 500.0), 2)
        action_type = random.choice(['CREDIT', 'DEBIT'])
        balance_after = round(random.uniform(50.0, 5000.0), 2)
        
        random_days_ago = random.randint(0, 365)
        timestamp = datetime.now() - timedelta(days=random_days_ago)
        
        log_data.append((guest_id, amount_changed, action_type, balance_after, timestamp))

    insert_query = """
        INSERT INTO wallet_audit_logs (guest_id, amount_changed, action_type, balance_after, timestamp) 
        VALUES %s
    """
    execute_values(cursor, insert_query, log_data)
    print("Audit logs inserted successfully!")

def main():
    conn = None
    try:
        conn = connect_db()
        cursor = conn.cursor()

        # Step 1: "Coordinate" by fetching the real IDs generated by Member 1
        guest_ids = fetch_existing_ids(cursor, 'guests')
        property_ids = fetch_existing_ids(cursor, 'properties')

        if not guest_ids or not property_ids:
            print("Error: The guests or properties tables are empty. Member 1 must seed them first.")
            return

        # Step 2: Generate your assigned relational data
        generate_and_insert_bookings(cursor, guest_ids, property_ids, 50000)
        generate_and_insert_audit_logs(cursor, guest_ids, 25000)

        conn.commit()

    except Exception as e:
        print(f"Database error: {e}")
        if conn:
            conn.rollback()
    finally:
        if conn:
            cursor.close()
            conn.close()
            print("Database connection closed.")

if __name__ == "__main__":
    main()